
export const ROUTES = {
  home: "/",
  aboutUs: "/about-us",
  leadership: "/about-us/leadership",
  boardOfDirectors: "/about-us/board-of-directors",
  partners: "/about-us/partners",
  investors: "/about-us/investors",
  privacy: "/privacy",
  terms: "/terms",
  accessibility: "/compliance/accessibility",
  services: "/services",
  aiSolutions: "/services/ai-solutions",
  saasDevelopment: "/services/saas-development",
  cloudHosting: "/services/cloud-hosting",
  automation: "/services/automation",
  customIntegrations: "/services/custom-integrations",
  innovationLab: "/innovation-lab",
  rnd: "/innovation-lab/rnd",
  aiResearch: "/innovation-lab/ai-research",
  patents: "/innovation-lab/patents",
  careers: "/careers",
  careersJobs: "/careers/jobs",
  lifeAtCivora: "/careers/life",
  internships: "/careers/internships",
  projects: "/projects",
  caseStudies: "/projects/case-studies",
  clientSuccessStories: "/projects/client-success-stories",
  contact: "/contact",
  salesInquiry: "/contact/sales",
  helpCenter: "/support/help-center",
  technicalSupport: "/support/technical-support",
  gdpr: "/compliance/gdpr",
  iso: "/compliance/iso",
  dataSecurity: "/compliance/security",
};
