
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// REMOVE THE GENERIC type parameter Database for now!
// import type { Database } from './types';

const SUPABASE_URL = "https://xmhglmcbjzrjykgigxxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtaGdsbWNianpyanlrZ2lneHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDU0MTksImV4cCI6MjA2NTQ4MTQxOX0.VBOk898luvo_ZL-t8O6y68HPPqE4j_2eAd4azNDcP6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// REMOVE THE GENERIC: createClient<Database>
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
